---@alias CreatureAbilityType
---|`ABILITY_TAXPAYER`
---|`ABILITY_BASH`
---|`ABILITY_SCATTER_SHOT`
---|`ABILITY_PRECISE_SHOT`
---|`ABILITY_ENRAGED`
---|`ABILITY_LARGE_SHIELD`
---|`ABILITY_SHIELD_OTHER`
---|`ABILITY_UNLIMITED_RETALIATION`
---|`ABILITY_IMMUNITY_TO_BLIND`
---|`ABILITY_BATTLE_DIVE`
---|`ABILITY_NO_MELEE_PENALTY`
---|`ABILITY_JOUSTING`
---|`ABILITY_LAY_HANDS`
---|`ABILITY_IMMUNITY_TO_BERSERK`
---|`ABILITY_RESURRECT_ALLIES`
---|`ABILITY_DEMONIC`
---|`ABILITY_MANA_DESTROYER`
---|`ABILITY_MANA_STEALER`
---|`ABILITY_EXPLOSION`
---|`ABILITY_NO_ENEMY_RETALIATION`
---|`ABILITY_THREE_HEADED_ATTACK`
---|`ABILITY_RANGED_RETALIATE`
---|`ABILITY_CHAIN_SHOT`
---|`ABILITY_FEAR`
---|`ABILITY_FRIGHT_AURA`
---|`ABILITY_VORPAL_SWORD`
---|`ABILITY_BALOR_SUMMONIG`
---|`ABILITY_UNDEAD`
---|`ABILITY_WEAKENING_STRIKE`
---|`ABILITY_INCORPOREAL`
---|`ABILITY_MANA_DRAIN`
---|`ABILITY_LIFE_DRAIN`
---|`ABILITY_DEATH_CLOUD`
---|`ABILITY_HARM_TOUCH`
---|`ABILITY_CURSING_ATTACK`
---|`ABILITY_HORROR_OF_THE_DEATH`
---|`ABILITY_SPRAY_ATTACK`
---|`ABILITY_WAR_DANCE`
---|`ABILITY_ELVES_DOUBLE_SHOT`
---|`ABILITY_WARDING_ARROWS`
---|`ABILITY_MANA_FEED`
---|`ABILITY_AURA_OF_MAGIC_RESISTANCE`
---|`ABILITY_BLINDING_ATTACK`
---|`ABILITY_ENTANGLING_ROOTS`
---|`ABILITY_TAKE_ROOTS`
---|`ABILITY_ACID_BREATH`
---|`ABILITY_IMMUNITY_TO_EARTH`
---|`ABILITY_REPAIR`
---|`ABILITY_ELEMENTAL`
---|`ABILITY_IMMUNITY_TO_AIR`
---|`ABILITY_IMMUNITY_TO_FIRE`
---|`ABILITY_IMMUNITY_TO_WATER`
---|`ABILITY_MECHANICAL`
---|`ABILITY_IMMUNITY_TO_SLOW`
---|`ABILITY_MAGIC_PROOF_50`
---|`ABILITY_MAGIC_PROOF_75`
---|`ABILITY_MAGIC_ATTACK`
---|`ABILITY_NO_RANGE_PENALTY`
---|`ABILITY_ENERGY_CHANNEL`
---|`ABILITY_RANDOM_CASTER`
---|`ABILITY_MAGIC_PROOF_25`
---|`ABILITY_RANDOM_CASTER_BLESS`
---|`ABILITY_DASH`
---|`ABILITY_IMMUNITY_TO_MIND_CONTROL`
---|`ABILITY_CALL_LIGHTNING`
---|`ABILITY_RANGE_PENALTY`
---|`ABILITY_POISONOUS_ATTACK`
---|`ABILITY_STRIKE_AND_RETURN`
---|`ABILITY_BRAVERY`
---|`ABILITY_DOUBLE_ATTACK`
---|`ABILITY_RIDER_CHARGE`
---|`ABILITY_LIZARD_BITE`
---|`ABILITY_SIX_HEADED_ATTACK`
---|`ABILITY_REGENERATION`
---|`ABILITY_WHIP_STRIKE`
---|`ABILITY_FIRE_BREATH`
---|`ABILITY_IMMUNITY_TO_MAGIC`
---|`ABILITY_FIRE_SHIELD`
---|`ABILITY_DEADLY_STRIKE`
---|`ABILITY_REBIRTH`
---|`ABILITY_ARMORED`
---|`ABILITY_SHIELD_WALL`
---|`ABILITY_WOUND`
---|`ABILITY_PAW_STRIKE`
---|`ABILITY_BERSERKER_RAGE`
---|`ABILITY_FIRE_PROOF_50`
---|`ABILITY_MARK_OF_FIRE`
---|`ABILITY_CROSS_ATTACK`
---|`ABILITY_STORMSTRIKE`
---|`ABILITY_FLAMEWAVE`
---|`ABILITY_FLAMESTRIKE`
---|`ABILITY_MAGMA_SHIELD`
---|`ABILITY_BRUTALITY`
---|`ABILITY_CLEAVE`
---|`ABILITY_PACK_DIVE`
---|`ABILITY_BATTLE_FRENZY`
---|`ABILITY_PURGER`
---|`ABILITY_CHAMPION_CHARGE`
---|`ABILITY_PACK_HUNTER`
---|`ABILITY_HOWL`
---|`ABILITY_AGILITY`
---|`ABILITY_HEXING_ATTACK`
---|`ABILITY_RIDE_BY_ATTACK`
---|`ABILITY_DEMON_RAGED`
---|`ABILITY_FIERCE_RETALIATION`
---|`ABILITY_TAUNT`
---|`ABILITY_IMMUNITY_TO_HYPNOTIZE`
---|`ABILITY_VENOM`
---|`ABILITY_SYPHON_MANA`
---|`ABILITY_LEAP`
---|`ABILITY_SEDUCE`
---|`ABILITY_SEARING_AURA`
---|`ABILITY_AXE_OF_SLAUGHTER`
---|`ABILITY_SUMMON_OTHER`
---|`ABILITY_INVISIBILITY`
---|`ABILITY_IMMUNITY_TO_CURSE`
---|`ABILITY_AURA_OF_BRAVERY`
---|`ABILITY_ACID_BLOOD`
---|`ABILITY_INCINERATE`
---|`ABILITY_TREEANT_UNION`
---|`ABILITY_PIERCING_ARROW`
---|`ABILITY_POWER_FEED`
---|`ABILITY_BOND_OF_LIGHT`
---|`ABILITY_RAGE_OF_THE_FOREST`
---|`ABILITY_RAINBOW_BREATH`
---|`ABILITY_WEAKENING_AURA`
---|`ABILITY_AMMO_STEAL`
---|`ABILITY_SLEEPING_STRIKE`
---|`ABILITY_DEATH_WAIL`
---|`ABILITY_SORROW_STRIKE`
---|`ABILITY_SABOTAGE`
---|`ABILITY_AURA_OF_FIRE_VULNERABILITY`
---|`ABILITY_AURA_OF_ICE_VULNERABILITY`
---|`ABILITY_AURA_OF_LIGHTNING_VULNERABILITY`
---|`ABILITY_ENCHANTED_OBSIDIAN`
---|`ABILITY_DESTRUCTION_MAGIC_MAGNETISM`
---|`ABILITY_ELDRITCH_AURA`
---|`ABILITY_LUCK_GAMBLER`
---|`ABILITY_WHIRLWIND`
---|`ABILITY_CALL_STORM`
---|`ABILITY_HOLD_GROUND`
---|`ABILITY_PREPARED_POSITION`
---|`ABILITY_HARPOON_STRIKE`
---|`ABILITY_BEAR_ROAR`
---|`ABILITY_ANTI_GIANT`
---|`ABILITY_BATTLE_RAGE`
---|`ABILITY_STORMBOLT`
---|`ABILITY_LIQUID_FLAME_BREATH`
---|`ABILITY_MANEURE`
---|`ABILITY_LIGHTNING_BREATH`
---|`ABILITY_SCAVENGER`
---|`ABILITY_CRYSTAL_SCALES`
---|`ABILITY_CRUSHING_BLOW`
---|`ABILITY_PRESENCE_OF_COMMANDER`
---|`ABILITY_COWARDICE`
---|`ABILITY_SET_SNARES`
---|`ABILITY_DEFILE_MAGIC`
---|`ABILITY_SACRIFICE_GOBLIN`
---|`ABILITY_FAST_ATTACK`
---|`ABILITY_ORDER_OF_THE_CHIEF`
---|`ABILITY_SWALLOW_GOBLIN`
---|`ABILITY_GOBLIN_THROWER`
---|`ABILITY_EVIL_EYE`
---|`ABILITY_FLYER`
---|`ABILITY_AURA_OF_EARTH_VULNERABILITY`
---|`ABILITY_DOUBLE_SHOT`
---|`ABILITY_TREACHERY`
---|`ABILITY_AVENGING_FLAME`
ABILITY_TAXPAYER = 1
ABILITY_BASH = 2
ABILITY_SCATTER_SHOT = 3
ABILITY_PRECISE_SHOT = 4
ABILITY_ENRAGED = 5
ABILITY_LARGE_SHIELD = 6
ABILITY_BASH = 7
ABILITY_SHIELD_OTHER = 8
ABILITY_UNLIMITED_RETALIATION = 9
ABILITY_IMMUNITY_TO_BLIND = 10
ABILITY_BATTLE_DIVE = 11
ABILITY_NO_MELEE_PENALTY = 12
ABILITY_JOUSTING = 13
ABILITY_LAY_HANDS = 14
ABILITY_IMMUNITY_TO_BERSERK = 15
ABILITY_RESURRECT_ALLIES = 16
ABILITY_DEMONIC = 17
ABILITY_MANA_DESTROYER = 18
ABILITY_MANA_STEALER = 19
ABILITY_EXPLOSION = 20
ABILITY_NO_ENEMY_RETALIATION = 21
ABILITY_THREE_HEADED_ATTACK = 22
ABILITY_RANGED_RETALIATE = 23
ABILITY_CHAIN_SHOT = 24
ABILITY_FEAR = 25
ABILITY_FRIGHT_AURA = 26
ABILITY_VORPAL_SWORD = 27
ABILITY_BALOR_SUMMONIG = 28
ABILITY_UNDEAD = 29
ABILITY_WEAKENING_STRIKE = 30
ABILITY_INCORPOREAL = 31
ABILITY_MANA_DRAIN = 32
ABILITY_LIFE_DRAIN = 33
ABILITY_DEATH_CLOUD = 34
ABILITY_HARM_TOUCH = 35
ABILITY_CURSING_ATTACK = 36
ABILITY_HORROR_OF_THE_DEATH = 37
ABILITY_SPRAY_ATTACK = 38
ABILITY_WAR_DANCE = 39
ABILITY_ELVES_DOUBLE_SHOT = 40
ABILITY_WARDING_ARROWS = 41
ABILITY_MANA_FEED = 42
ABILITY_AURA_OF_MAGIC_RESISTANCE = 43
ABILITY_BLINDING_ATTACK = 44
ABILITY_ENTANGLING_ROOTS = 45
ABILITY_TAKE_ROOTS = 46
ABILITY_ACID_BREATH = 47
ABILITY_IMMUNITY_TO_EARTH = 48
ABILITY_REPAIR = 49
ABILITY_ELEMENTAL = 50
ABILITY_IMMUNITY_TO_AIR = 51
ABILITY_IMMUNITY_TO_FIRE = 52
ABILITY_IMMUNITY_TO_WATER = 53
ABILITY_MECHANICAL = 54
ABILITY_IMMUNITY_TO_SLOW = 55
ABILITY_MAGIC_PROOF_50 = 56
ABILITY_MAGIC_PROOF_75 = 57
ABILITY_MAGIC_ATTACK = 58
ABILITY_NO_RANGE_PENALTY = 59
ABILITY_ENERGY_CHANNEL = 60
ABILITY_RANDOM_CASTER = 61
ABILITY_MAGIC_PROOF_25 = 62
ABILITY_RANDOM_CASTER_BLESS = 63
ABILITY_DASH = 64
ABILITY_IMMUNITY_TO_MIND_CONTROL = 65
ABILITY_CALL_LIGHTNING = 66
ABILITY_RANGE_PENALTY = 67
ABILITY_POISONOUS_ATTACK = 68
ABILITY_STRIKE_AND_RETURN = 69
ABILITY_BRAVERY = 70
ABILITY_DOUBLE_ATTACK = 71
ABILITY_RIDER_CHARGE = 72
ABILITY_LIZARD_BITE = 73
ABILITY_THREE_HEADED_ATTACK = 74
ABILITY_SIX_HEADED_ATTACK = 75
ABILITY_REGENERATION = 76
ABILITY_WHIP_STRIKE = 77
ABILITY_FIRE_BREATH = 78
ABILITY_IMMUNITY_TO_MAGIC = 79
ABILITY_FIRE_SHIELD = 80
ABILITY_DEADLY_STRIKE = 81
ABILITY_REBIRTH = 82
ABILITY_ARMORED = 83
ABILITY_SHIELD_WALL = 84
ABILITY_WOUND = 85
ABILITY_PAW_STRIKE = 86
ABILITY_BERSERKER_RAGE = 87
ABILITY_FIRE_PROOF_50 = 88
ABILITY_MARK_OF_FIRE = 89
ABILITY_CROSS_ATTACK = 90
ABILITY_STORMSTRIKE = 91
ABILITY_FLAMEWAVE = 92
ABILITY_FLAMESTRIKE = 93
ABILITY_MAGMA_SHIELD = 94
ABILITY_BRUTALITY = 95
ABILITY_CLEAVE = 96
ABILITY_PACK_DIVE = 97
ABILITY_BATTLE_FRENZY = 98
ABILITY_PURGER = 99
ABILITY_CHAMPION_CHARGE = 100
ABILITY_PACK_HUNTER = 101
ABILITY_HOWL = 102
ABILITY_AGILITY = 103
ABILITY_HEXING_ATTACK = 104
ABILITY_RIDE_BY_ATTACK = 105
ABILITY_DEMON_RAGED = 106
ABILITY_FIERCE_RETALIATION = 107
ABILITY_TAUNT = 108
ABILITY_IMMUNITY_TO_HYPNOTIZE = 109
ABILITY_VENOM = 110
ABILITY_SYPHON_MANA = 111
ABILITY_LEAP = 112
ABILITY_FIRE_BREATH = 113
ABILITY_SEDUCE = 114
ABILITY_SEARING_AURA = 115
ABILITY_AXE_OF_SLAUGHTER = 116
ABILITY_SUMMON_OTHER = 117
ABILITY_INVISIBILITY = 118
ABILITY_IMMUNITY_TO_CURSE = 119
ABILITY_AURA_OF_BRAVERY = 120
ABILITY_ACID_BLOOD = 121
ABILITY_INCINERATE = 122
ABILITY_TREEANT_UNION = 123
ABILITY_PIERCING_ARROW = 124
ABILITY_POWER_FEED = 125
ABILITY_BOND_OF_LIGHT = 126
ABILITY_RAGE_OF_THE_FOREST = 127
ABILITY_RAINBOW_BREATH = 128
ABILITY_WEAKENING_AURA = 129
ABILITY_AMMO_STEAL = 130
ABILITY_SLEEPING_STRIKE = 131
ABILITY_DEATH_WAIL = 132
ABILITY_SORROW_STRIKE = 133
ABILITY_SABOTAGE = 134
ABILITY_AURA_OF_FIRE_VULNERABILITY = 135
ABILITY_AURA_OF_ICE_VULNERABILITY = 136
ABILITY_AURA_OF_LIGHTNING_VULNERABILITY = 137
ABILITY_ENCHANTED_OBSIDIAN = 138
ABILITY_DESTRUCTION_MAGIC_MAGNETISM = 139
ABILITY_ELDRITCH_AURA = 140
ABILITY_LUCK_GAMBLER = 141
ABILITY_WHIRLWIND = 142
ABILITY_CALL_STORM = 143
ABILITY_HOLD_GROUND = 144
ABILITY_PREPARED_POSITION = 145
ABILITY_HARPOON_STRIKE = 146
ABILITY_BEAR_ROAR = 147
ABILITY_ANTI_GIANT = 148
ABILITY_BATTLE_RAGE = 149
ABILITY_STORMBOLT = 150
ABILITY_LIQUID_FLAME_BREATH = 151
ABILITY_MANEURE = 152
ABILITY_LIGHTNING_BREATH = 153
ABILITY_SCAVENGER = 154
ABILITY_CRYSTAL_SCALES = 155
ABILITY_CRUSHING_BLOW = 156
ABILITY_PRESENCE_OF_COMMANDER = 157
ABILITY_COWARDICE = 158
ABILITY_SET_SNARES = 159
ABILITY_DEFILE_MAGIC = 160
ABILITY_SACRIFICE_GOBLIN = 161
ABILITY_FAST_ATTACK = 162
ABILITY_ORDER_OF_THE_CHIEF = 163
ABILITY_SWALLOW_GOBLIN = 164
ABILITY_GOBLIN_THROWER = 165
ABILITY_EVIL_EYE = 166
ABILITY_FLYER = 167
ABILITY_AURA_OF_EARTH_VULNERABILITY = 168
ABILITY_DOUBLE_SHOT = 169
ABILITY_TREACHERY = 170
ABILITY_AVENGING_FLAME = 171

__end_import()